name: mapper-tests

on:
  pull_request:
  push:
    branches:
      - "main"
      - "develop"
  workflow_call:

jobs:
  check-pre-commit-hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --verbose

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Configure
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: sentinelhub.config --sh_client_id "$CLIENT_ID" --sh_client_secret "$CLIENT_SECRET"

      - name: Run tests
        run: pytest
